"""add campaign and edit users

Revision ID: 07d0f5613ed2
Revises: 4ba8f54bee55
Create Date: 2025-09-29 11:30:46.554355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d0f5613ed2'
down_revision: Union[str, Sequence[str], None] = '4ba8f54bee55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_user',
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_user_id'), 'anonymous_user', ['id'], unique=False)
    op.create_table('invalidate_token',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invalidate_token_id'), 'invalidate_token', ['id'], unique=False)
    op.create_index(op.f('ix_invalidate_token_jti'), 'invalidate_token', ['jti'], unique=True)
    op.create_table('supporter',
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anonymous_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND anonymous_id IS NULL) OR (user_id IS NULL AND anonymous_id IS NOT NULL)', name='ck_supporter_type'),
    sa.ForeignKeyConstraint(['anonymous_id'], ['anonymous_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supporter_id'), 'supporter', ['id'], unique=False)
    op.drop_index(op.f('ix_invalidatetoken_id'), table_name='invalidatetoken')
    op.drop_index(op.f('ix_invalidatetoken_jti'), table_name='invalidatetoken')
    op.drop_table('invalidatetoken')
    op.add_column('user', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'phone')
    op.create_table('invalidatetoken',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('invalidatetoken_pkey'))
    )
    op.create_index(op.f('ix_invalidatetoken_jti'), 'invalidatetoken', ['jti'], unique=True)
    op.create_index(op.f('ix_invalidatetoken_id'), 'invalidatetoken', ['id'], unique=False)
    op.drop_index(op.f('ix_supporter_id'), table_name='supporter')
    op.drop_table('supporter')
    op.drop_index(op.f('ix_invalidate_token_jti'), table_name='invalidate_token')
    op.drop_index(op.f('ix_invalidate_token_id'), table_name='invalidate_token')
    op.drop_table('invalidate_token')
    op.drop_index(op.f('ix_anonymous_user_id'), table_name='anonymous_user')
    op.drop_table('anonymous_user')
    # ### end Alembic commands ###
