"""edit decimal

Revision ID: 3436c3f3f8ad
Revises: 68586ee43ab6
Create Date: 2025-09-29 13:04:47.906207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3436c3f3f8ad'
down_revision: Union[str, Sequence[str], None] = '68586ee43ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'goal_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('campaign', 'current_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('campaign', 'used_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'used_amount',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('campaign', 'current_amount',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('campaign', 'goal_amount',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
